(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1170,
	height: 326,
	fps: 40,
	color: "#999999",
	manifest: [
		{src:"/catalog/view/javascript/banner_html5/dark_panel.png", id:"dark_panel"},
		{src:"/catalog/view/javascript/banner_html5/fon.jpg", id:"fon"},
		{src:"/catalog/view/javascript/banner_html5/fon_element.jpg", id:"fon_element"}
	]
};



// symbols:



(lib.dark_panel = function() {
	this.initialize(img.dark_panel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,722,123);


(lib.fon = function() {
	this.initialize(img.fon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1170,326);


(lib.fon_element = function() {
	this.initialize(img.fon_element);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1112,1112);


(lib.txt33 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgkxAFsIAAh5Ik6AAIAAB5IhPAAIAAibQAAgTALgKQALgLATABIAKAAIAbh2IAbhvQALgvAQgfQARggAZgSQAYgSAfgJQAegHAmAAQAiAAAXACIAfAFQAPADALAJQAMAJgBAVIAAFWIAJAAQATgBALALQALAKAAATIAACbgEgm6gCSQgSAFgNAMQgNAMgKAVQgKATgIAgIgNAwIgMA7IgOA5IgMAzIDSAAIAAk8QgGgBgNgCQgNgBgOAAQgXAAgSAEgEApjADuQgPgPAAgUQAAgVAPgPQAQgOAVAAQAUAAAPAOQAPAPABAVQgBAUgPAPQgPAQgUAAQgVAAgQgQgAIUD4IgqgBIgfgCIgRgCIAAmlQAAgTALgJQAKgJAUAAQANAAALADIANAGIAACPIAjgDQAVgBAYAAQAnAAAmAHQAlAGAdARQAdARARAcQATAegBAwQAABTg5ApQg6AnhyAAIgugBgAIoABIggACIAACuIAfADIAuABQAbAAAXgGQAYgEARgMQAQgKAKgTQAKgRAAgbQAAgdgLgRQgMgSgSgIQgSgJgXgDQgYgCgXAAIgrABgEAm4ADzIAAlSQgbAlggAuIhABZIg8BaIg0BMIhQAAIAAmlQAAgTAKgJQALgJAUAAQANAAAKADIAPAFIAAFEIBfiFIBhiHIARgYQAJgLAKgJQALgIAMgGQAMgFAPAAQANAAAJACQAJACAGADIAAHCgAbSDzIAAmcQAAguAxAAIEBAAQAoAAAAAkQAAANgDAKIgGAOIkAAAIAAB0IDYAAQAoAAAAAiQgBAMgDAKQgEALgDADIj1AAIAAB+IEGAAIAABJgAQkDzIAAmlQAAgTAMgJQAKgJAUAAQANAAALADIANAFIAAF5ICwAAIAAlcQAAgTALgJQALgJATAAQAOAAAKADIAOAFIAAF5ICvAAIAAlcQAAgTALgJQALgJAUAAQANAAAKADIAOAFIAAHCgAN0DzIAAmlQAAgTALgJQALgJAUAAQAMAAALADIAPAFIAAHCgAEJDzIAAmEIgUgDIgcgBQgWAAgTAEQgRAFgOALQgOAMgKAVQgKATgIAgQgMApgIAmIgSBQQgIAegLAhQgMAjgVAfIhYAAQAXglAOghQANggAJgfIAKglIAIgoIAKgpIALgzQALgvARgfQARggAZgSQAYgSAfgJQAfgHAnAAQAgAAAYACIAhAFQAPADALAJQALAJAAAVIAAGfgAirDzIgJgYIgLgfIgNgiIgNggIjgAAIgbBFIgSA0IhRAAQARguAVgzIArhrIAwhtIAwhtQANgbAOgLQAQgKAXAAIARABIAPAGIALAFIAFADQALASARAlIAlBTIAoBeIAnBeIAfBPIATAygAlahoIgXAzIgWA1IgVA0ICpAAIgWg1IgYg6IgVg0IgRgjIgTAqgAq3DzIgCgmIgDg9IgFhJIgDhIIgEg8IgCglIgQAgIgWAsIgZAxIgYAxIgVAsIgQAhIhCAAQgIgSgQggIgghEIgkhGIggg9IgCArIgDA5IgEBEIgEBEIgDA8IgCArIhPAAIADgzIADhJIAFhUIAEhTIAGhJIACgyQACgYAPgKQAOgKAUAAQAUAAANAGQANAGAGAFIAYAxIAkBIIAmBMIAgA8IAdg4IAihDIAfhBIAYguQAJgUAPgKQAOgKAWAAQATAAANAFQAOAFADADIADA2IAFBQIAFBYIAFBaIAFBPIADA2gA24DzIAAisQgJABgWACQgXABgXAAIgWAAIgWgCQgKANgOAYIgcAxIgaAxIgRAjIhdAAIAYgwIAcgxIAcgwQAPgZAOgSQgogTgYgfQgWgcAAgyQAAhFA0goQA0gnBpAAQA0gBAcADQAbADAKACQAQABAKAKQALAKAAAVIAAGfgA5DiUQgZAHgOALQgPAMgGAOQgGAQAAAQQAAASAGAPQAGAPAPALQAQALAYAEQAZAGAkAAQAhAAASgCIAagDIAAiZQgGgBgSgBQgRgDgiAAQgmABgaAGgA97DzIAAmEIgVgDIgcgBQgWAAgSAEQgSAFgOALQgNAMgKAVQgLATgIAgQgLApgJAmIgSBQQgIAegLAhQgLAjgVAfIhaAAQAXglAOghQANggAIgfIAKglIAKgoIAKgpIAMgzQALgvARgfQARggAYgSQAYgSAfgJQAfgHAnAAQAhAAAYACIAgAFQAQADAKAJQALAJAAAVIAAGfgEAphABfIAAkSQAAgTALgIQALgJASAAQAMAAALADIANAFIAAEugEAkGgEMQgXgLgOgOQgOgPgGgSQgGgRgBgOIAzgGQAIAZARANQARANAfABQA6AAAOg0IAyAGQAAAOgHARQgFASgPAPQgOAOgYALQgXAKgiAAQglAAgXgKg");
	this.shape.setTransform(779.9,163.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(505.2,127.1,549.4,72.9);


(lib.txt32 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A/2ElIAAh5Ik6AAIAAB5IhPAAIAAibQAAgTALgKQALgKATAAIAKAAIAbh0IAbhxQALgvAQgfQARgfAZgTQAYgSAfgJQAegHAmAAQAiAAAXADIAfAEQAPADALAJQAMAJgBAWIAAFVIAJAAQATAAALAKQALAKAAATIAACbgEgh/gDYQgSAEgNAMQgNAMgKAVQgKAUgIAfIgNAzIgMA6IgOA3IgMAzIDSAAIAAk8QgGgBgNgBQgNgCgOAAQgXAAgSAFgEAkoACnQgPgPAAgUQAAgUAPgPQAQgPAVAAQAUAAAPAPQAPAPABAUQgBAUgPAPQgPAQgUAAQgVAAgQgQgAijC1IArhBQAVgjAWglIhciSQgng9gQggIgRggQgHgLABgOQAAgNAHgLQAIgLAVAAQALAAAKADIAPAFIAZAvIAkBBIApBHIApBDQAdg2AZg2IA2hqIAJgSQAFgIAGgGQAHgGAIgCQAJgDANAAQARAAALAGIAQAJQgeBAgeA6QgfA6gfA4Ig9BrQghA2gjA3gEAh8ACsIAAjIIjsAAIAADIIhPAAIAAmlQgBgTALgJQAMgJAUAAQAMAAALADIAOAFIAACwIDsAAIAAiTQAAgTALgJQALgJAUAAQANAAAKADIAPAGIAAHBgAaQCsIAAlSQgbAlggAuIg/BaIg9BaIg1BLIhPAAIAAmlQAAgTAKgJQALgJAUAAQANAAAKADIAOAFIAAFEIBgiFIBhiHIARgYQAKgLAJgJQAKgIANgFQAMgGAPAAQANAAAJACQAKACAFADIAAHCgASkCsIAAiqQgXAFgZADQgZADglAAQgiAAgigGQghgHgagOQgagRgPgeQgQgeAAgvIAAhvQAAgTALgJQAMgJATAAQAMAAALADIAPAFIAABwQgBAeAGAUQAFAVAOANQANANAXAGQAWAFAiAAQAiAAAVgCQAWgDAVgFIAAi1QgBgTAMgJQALgJAUAAQANAAALADIANAFIAAHCgAL5CsIgigxIglgyIgmgwIglgrQgPACgNAAIgaAAIAAC8IhOAAIAAi8IgaAAIgOAAIgNgCIgmArIgmAwIglAyIgiAxIhcAAQARgdAWgeIArg8IAsg3IArgyQgOgKgLgMQgKgMgJgMIghguQgRgWgNgWQgPgVgIgRQgJgRAAgLQABgNAIgJQAKgKAQAAQANAAAIADIANAFIAPAYIAZAnIAdAtQAPAWANAQQAJAMAJAJQAIAIAIAGQAJAFALADQAKACAOAAIASAAIAAiiQAAgTAKgJQALgJAVAAQAMAAAKADIAOAFIAAC/IASAAQAYAAAOgIQAPgHASgUQAbgiASgeQASgeAOgVQAOgXAPgNQAPgNAWAAQATAAALAFQALAFAIAHIg0BQQgdAsggAvQgJAMgLAMQgLAMgNAKIAqAyQAWAaAVAdQAXAeAVAeQAWAeASAdgAl8CsIgCgmIgDg9IgFhJIgDhHIgEg9IgCglIgQAhIgWArIgZAzIgYAvIgVAsIgQAhIhCAAQgIgSgQggIgghCIgkhIIggg9IgCArIgDA7IgEBCIgEBEIgDA8IgCArIhPAAIADgzIADhJIAFhSIAEhVIAGhJIACgyQACgYAPgKQAOgKAUAAQAUAAANAGQANAGAGAFIAYAyIAkBHIAmBMIAgA/IAdg5IAihEIAfhBIAYgvQAJgUAPgKQAOgKAWAAQATAAANAFQAOAFADAEIADA2IAFBPIAFBaIAFBZIAFBOIADA2gAx9CsIAAisQgJACgWABQgXABgXAAIgWAAIgWgCQgKANgOAYIgcAxIgaAxIgRAjIhdAAIAYgvIAcgyIAcgwQAPgYAOgRQgogSgYgfQgWgfAAgxQAAhFA0gpQA0gnBpAAQA0AAAcACQAbADAKACQAQACAKAKQALAJAAAWIAAGegA0IjaQgZAGgOAMQgPALgGAPQgGAPAAAQQAAATAGAPQAGAPAPALQAQAKAYAGQAZAGAkAAQAhAAASgBIAagDIAAicQgGgBgSgBQgRgCgiAAQgmAAgaAHgA5ACsIAAmEIgVgCIgcgBQgWAAgSAEQgSAEgOAMQgNAMgKAUQgLAUgIAfQgLApgJAoIgSBOQgIAegLAiQgLAjgVAeIhaAAQAXglAOghQANggAIgeIAKgmIAKgmIAKgrIAMgzQALgvARgfQARgfAYgTQAYgSAfgJQAfgHAnAAQAhAAAYADIAgAEQAQADAKAJQALAJAAAWIAAGegEAkmAAYIAAkSQAAgTALgIQALgJASAAQAMAAALADIANAFIAAEug");
	this.shape.setTransform(748.4,170.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(505.2,141.2,486.4,58.8);


(lib.txt31 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AUIElIAAh5IouAAIAAmlQAAgTAMgJQAKgJAUAAQAMAAAMADIANAFIAAF5ICwAAIAAlcQAAgTAKgJQALgJAUAAQANAAALADIANAFIAAF5ICwAAIAAlcQAAgTALgJQALgJAUAAQAMAAALADIAOAFIAAF5IAKAAQATAAAKAKQAKAKAAATIAACbgEgg3AElIAAh5Ik5AAIAAB5IhPAAIAAibQAAgTAKgKQALgKATAAIAKAAIAbh0IAbhxQALgvARgfQARgfAYgTQAYgSAfgJQAfgHAmAAQAhAAAXADIAgAEQAPADALAJQALAJAAAWIAAFVIAJAAQATAAAKAKQALAKAAATIAACbgEgjAgDYQgRAEgNAMQgNAMgLAVQgKAUgIAfIgMAzIgNA6IgNA3IgMAzIDSAAIAAk8QgGgBgNgBQgNgCgOAAQgYAAgSAFgEAlpACnQgPgPAAgUQAAgUAPgPQAQgPAVAAQAUAAAPAPQAPAPAAAUQAAAUgPAPQgPAQgUAAQgVAAgQgQgEAi9ACsIAAjIIjsAAIAADIIhQAAIAAmlQAAgTALgJQAMgJATAAQAMAAALADIAPAFIAACwIDsAAIAAiTQgBgTALgJQALgJAUAAQAOAAAKADIAPAGIAAHBgAbRCsIAAlSQgbAlggAuIhABaIg9BaIg0BLIhQAAIAAmlQAAgTALgJQALgJATAAQANAAAKADIAPAFIAAFEIBfiFIBiiHIARgYQAJgLAKgJQAKgIAMgFQAMgGAQAAQANAAAIACQAKACAGADIAAHCgAIpCsIAAjIIjsAAIAADIIhPAAIAAmlQAAgTALgJQALgJAUAAQAMAAALADIAOAFIAACwIDsAAIAAiTQAAgTALgJQALgJATAAQAOAAAKADIAPAGIAAHBgAi8CsIAAmcQAAguAyAAID+AAQApAAAAAkQAAANgEAKIgGAOIj+AAIAAB0IDWAAQAoAAAAAkQAAAMgEALQgEAKgDADIjzAAIAAB8IEEAAIAABJgAlUCsIghgxIglgyIgmgwIgmgrQgOACgOAAIgZAAIAAC8IhPAAIAAi8IgZAAIgOAAIgNgCIgnArIgmAwIglAyIgiAxIhcAAQASgdAVgeIArg8IAsg3IArgyQgOgKgLgMQgKgMgIgMIgiguQgRgWgNgWQgOgVgJgRQgIgRAAgLQAAgNAJgJQAJgKAQAAQANAAAJADIAMAFIAQAYIAYAnIAeAtQAPAWANAQQAIAMAJAJQAIAIAJAGQAJAFALADQAKACANAAIASAAIAAiiQAAgTALgJQALgJAUAAQAMAAALADIAOAFIAAC/IASAAQAXAAAPgIQAPgHARgUQAbgiASgeQASgeAPgVQAOgXAPgNQAOgNAXAAQASAAALAFQAMAFAIAHIg0BQQgdAsghAvQgJAMgKAMQgLAMgNAKIAqAyQAVAaAWAdQAXAeAUAeQAWAeATAdgAy+CsIAAisQgJACgVABQgXABgXAAIgXAAIgVgCQgLANgOAYIgcAxIgaAxIgRAjIhcAAIAYgvIAcgyIAcgwQAOgYAOgRQgogSgXgfQgXgfAAgxQAAhFA0gpQA0gnBqAAQA0AAAcACQAbADAKACQAPACALAKQALAJAAAWIAAGegA1IjaQgaAGgOAMQgPALgGAPQgGAPAAAQQABATAFAPQAHAPAOALQAQAKAZAGQAYAGAlAAQAgAAASgBIAagDIAAicQgFgBgSgBQgSgCghAAQgmAAgaAHgA6BCsIAAmEIgUgCIgcgBQgWAAgTAEQgRAEgOAMQgOAMgKAUQgKAUgIAfQgMApgIAoIgSBOQgIAegLAiQgMAjgVAeIhaAAQAXglAOghQANggAJgeIAKgmIAKgmIAKgrIALgzQALgvARgfQARgfAZgTQAYgSAfgJQAfgHAnAAQAgAAAYADIAhAEQAPADALAJQALAJAAAWIAAGegEAlnAAYIAAkSQAAgTALgIQALgJASAAQAMAAAKADIAOAFIAAEug");
	this.shape.setTransform(754.9,170.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(505.2,141.2,499.3,58.8);


(lib.txt3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJGCwIAAhIIi8AAIAABIIgvAAIAAhcQAAgLAHgGQAGgGAMgBIAFAAIAQhDIARhFQAGgbAKgSQAKgUAPgKQAOgMATgEQASgGAXAAQATAAAOACIATADQAJACAHAGQAGAFAAANIAADKIAFAAQAMABAGAGQAHAGAAALIAABcgAH0h/QgLADgIAHQgHAHgGANQgGALgFATIgHAeIgIAjIgIAgIgHAeIB9AAIAAi7IgLgCIgRgBQgOABgKACgAl3CwIAAhIIi7AAIAABIIgvAAIAAhcQAAgLAGgGQAGgGAMgBIAGAAIAQhDIAQhFQAGgbALgSQAKgUAOgKQAPgMASgEQASgGAXAAQAUAAANACIAUADQAJACAGAGQAHAFAAANIAADKIAFAAQALABAHAGQAGAGAAALIAABcgAnJh/QgKADgIAHQgIAHgGANQgGALgFATIgHAeIgIAjIgIAgIgHAeIB9AAIAAi7IgLgCIgQgBQgOABgLACgAtFBlQgbgMgUgTQgUgUgLgaQgLgYAAgfQAAgfALgaQALgbAUgTQAUgTAbgMQAagLAfABQAfgBAbALQAbAMAUATQATATAMAbQALAaAAAfQAAAfgLAYQgMAagTAUQgUATgbAMQgbAKgfAAQgfAAgagKgAsyh8QgSAHgNANQgNANgHATQgHATAAAWQAAAWAHAQQAHASANAOQANANASAIQASAHAUAAQAVAAASgHQARgIANgNQANgOAHgSQAIgQAAgWQAAgWgIgTQgHgTgNgNQgNgNgRgHQgSgIgVAAQgUAAgSAIgANrBoIgGgNIgHgTIgHgVIgIgTIiGAAIgPApIgMAfIgwAAIAXg6IAag9IAchDIAdhBQAHgQAJgGQAJgHAPABIAKAAIAIADIAHAEIADABIAQAiIAXAxIAYA5IAXA3IASAvIALAdgAMChmIgNAeIgOAgIgNAhIBlAAIgMghIgPgjIgNgfIgKgVIgLAZgAEXBoIgUgdIgWgeIgWgdIgXgZIgQACIgQAAIAABvIgvAAIAAhvIgPAAIgIAAIgIgCIgXAZIgXAdIgWAeIgSAdIg3AAIAXgjIAagkIAYghIAagdQgIgGgHgHIgLgPIgSgbIgSgaIgOgWQgFgLAAgGQAAgIAGgGQAFgFAJAAQAIAAAGACIAHACIAHAPIAPAXIARAaIARAYIAKAMIALAIQAFADAGACQAGABAJABIAKAAIAAhiQAAgLAHgFQAGgGAMABQAIAAAGACIAIACIAABzIALAAQAOgBAJgEQAJgFAKgMQAQgUALgSIATgeQAJgOAIgHQAJgIANAAQAMAAAGACQAHADAFAFIgfAvQgRAbgUAbIgMAPQgGAHgIAGIAZAdQANAQANARIAaAkIAYAjgAkjBoIAAj1QAAgbAdAAICaAAQAYgBAAAWQAAAIgDAGIgDAIIiZAAIAABFICBAAQAYAAAAAWQAAAHgDAGIgDAIIiTAAIAABJICcAAIAAAsg");
	this.shape.setTransform(602.7,73);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(509.9,55.3,185.6,35.4);


(lib.txt2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhNG4QgZgLgTgTQgTgSgLgaQgLgZAAgdQAAgeALgaQALgYATgTQATgTAZgLQAagKAeAAQAbAAAaAKQAZALATATQATATALAYQALAaAAAeQAAAdgLAZQgLAagTASQgTATgZALQgaAKgbAAQgeAAgagKgAg6DeQgRAHgNANQgMANgHARQgHATAAAVQAAAUAHASQAHASAMAMQANANARAIQARAHAUAAQATAAAPgHQARgIANgNQAMgMAHgSQAHgSAAgUQAAgVgHgTQgHgRgMgNQgNgNgRgHQgPgHgTAAQgUAAgRAHgApnG4QgZgLgTgTQgTgSgLgaQgLgZAAgdQAAgeALgaQALgYATgTQATgTAZgLQAagKAeAAQAdAAAaAKQAZALATATQATATALAYQALAaAAAeQAAAdgLAZQgLAagTASQgTATgZALQgaAKgdAAQgeAAgagKgApUDeQgRAHgNANQgMANgHARQgHATAAAVQAAAUAHASQAHASAMAMQANANARAIQARAHAUAAQATAAARgHQARgIANgNQAMgMAHgSQAHgSAAgUQAAgVgHgTQgHgRgMgNQgNgNgRgHQgRgHgTAAQgUAAgRAHgEggdAG+QgSgDgNgEQgNgEgJgFIgOgHIAUgiIAMAHIASAGQALADANACQANACAQAAQAgAAATgLQASgKAAgUQAAgUgRgKQgSgKgeAAIgiAAQgXAAAAgUQAAgHACgGIAEgHIA1AAQAdAAAPgLQAPgLAAgRQAAgRgRgKQgRgLgeAAQgSAAgNAEQgNAEgIAFQgJAGgEAFIgGAIQgKgBgHgHQgIgGAAgJQAAgFACgFQACgFAFgFIAJgIQAGgEAKgFQALgEAPgDQAQgDAVAAQAcAAAVAGQAUAHANAKQAOAJAGANQAGANAAANQAAALgDAKQgEALgGAHQgGAIgIAGQgIAGgJAEQAOAEAJAGQAJAHAGAJQAGAIADAKQADAKAAAJQAAASgJAPQgIAOgPAKQgOALgVAFQgUAGgYAAQgXAAgSgDgANwG/IgXgCIgSgBIgJgBIAAjtQAAgaAbAAICHAAQAXAAAAAVQAAAHgCAGIgEAIIiGAAIAAA7IASgBIAYgBQAWAAAUADQAVAEAQAJQAPAJAKAQQAKAPAAAaQAAArgfAWQggAUg/ABIgZAAgAN8E/IgRACIAABVIAQABIAYABQAPAAAMgDQANgCAJgGQAJgFAFgJQAGgJAAgNQAAgOgHgJQgGgJgKgEQgJgEgNgBQgMgCgNAAIgWABgEAkfAG7IgFgNIgGgSIgIgUIgHgRIiAAAIgPAmIgLAeIguAAIAVg3IAZg+IAbg/IAcg/QAHgPAJgGQAIgGAOAAIAKABIAIADIAGADIADABIALAVIAFAMIAVAvIAXA3IAWA1IASAtIALAdgEAi7AD0IgNAcIgNAgIgMAeIBhAAIgMgfIgOghIgGgOIgHgQIgJgVIgLAZgAelG7IAAjdIhNAAQgXgBAAgUQAAgHADgGIADgIIDbAAQAWAAAAAVQAAAHgCAGIgDAIIhhAAIAADdgAZnG7IAAjtQAAgaAcAAICTAAQAXAAAAAVQAAAHgCAGIgEAIIiSAAIAABCIB8AAQAWAAAAAUQAAAHgCAHIgEAIIiMAAIAABIICWAAIAAApgAYBG7IAAh0IiHAAIAAB0IgtAAIAAjyQAAgLAGgFQAHgFALAAQAHAAAGACIAIACIAABmICHAAIAAhVQAAgLAHgFQAGgFALAAQAIAAAGACIAIADIAAECgAToG7IAAjCIgiAvIglA1IgjAzIgdArIguAAIAAjyQAAgLAGgFQAGgFAMAAQAHAAAGACIAIACIAAC7IA3hNIA4hOIAJgNQAFgGAGgGQAGgEAHgEQAHgCAJAAQAHAAAFABIAJACIAAEDgALkG7IgFgNIgGgSIgIgUIgHgRIiAAAIgPAmIgLAeIguAAIAVg3IAZg+IAbg/IAcg/QAHgPAJgGQAIgGAOAAIAKABIAIADIAGADIADABIALAVIAFAMIAVAvIAXA3IAWA1IASAtIALAdgAKAD0IgNAcIgNAgIgMAeIBhAAIgMgfIgOghIgGgOIgHgQIgJgVIgLAZgAGuG7IgTgcIgWgdIgWgcIgXgZIgKABIgMAAIgTAAIAABtIgtAAIAAjyQAAgVAXABQAIAAAGABIAIACIAABuIAQAAQAQAAALgGQAKgEAJgLQARgTAKgRIATgdQAIgMAIgIQAIgHAOAAQAKAAAGACIALAGIgeAuIgkA1IgMAOIgMAMIAYAcIAZAhIAZAiIAWAigAl3G7IAAjtQAAgaAcAAICPAAQAXAAAAAVQAAAHgDAGIgDAIIiPAAIAADdgAsWG7IAAh0IiHAAIAAB0IguAAIAAjyQAAgLAHgFQAGgFALAAQAIAAAGACIAIACIAABmICHAAIAAhVQAAgLAGgFQAHgFALAAQAHAAAGACIAIADIAAECgAwxG7IAAhiIgbAGQgOABgVAAQgUAAgTgDQgTgEgPgKQgPgKgJgRQgJgRAAgbIAAg/QAAgLAHgFQAGgFALAAQAIAAAGACIAIACIAABBQAAAQADAMQADAMAIAIQAIAHAMADQANADATAAQAUAAAMgBQANgBALgDIAAhoQAAgLAHgFQAGgFAMAAQAHAAAGACIAIACIAAEDgA0zG7IAAjCIgiAvIgkA1IgjAzIgeArIgtAAIAAjyQAAgLAGgFQAGgFALAAQAHAAAHACIAIACIAAC7IA2hNIA4hOIAKgNQAFgGAGgGQAFgEAHgEQAHgCAJAAQAHAAAGABIAIACIAAEDgA5MG7IAAjfIgMgCIgQAAQgNAAgKACQgKADgIAGQgIAIgGALQgGALgEATIgLAuIgLAtQgEARgHAUQgGAUgMARIg0AAQANgVAIgSQAIgTAFgRIAFgWIAGgXIAGgZIAGgdQAHgbAJgRQAKgSAOgLQAOgLASgEQASgFAWAAQATAAANACIATADQAJABAGAGQAGAEAAANIAADugEgiuAG7IAAjCIgiAvIglA1IgjAzIgdArIguAAIAAjyQAAgLAGgFQAGgFAMAAQAHAAAGACIAIACIAAC7IA3hNIA4hOIAJgNQAFgGAGgGQAGgEAHgEQAHgCAJAAQAHAAAFABIAJACIAAEDgAi8APQgtgRghghQghgggTgtQgTgsAAgzQAAg0ATgsQATgsAhghQAhggAtgSQAsgTA0AAQA0AAArATQAtASAhAgQAhAhATAsQASAsAAA0QAAAzgSAsQgTAtghAgQghAhgtARQgrASg0AAQg0AAgsgSgAiclsQgdANgWAWQgWAWgMAgQgMAfAAAlQAAAkAMAfQAMAfAWAWQAWAXAdANQAdAMAjAAQAjAAAegMQAbgNAWgXQAVgWAMgfQANgfAAgkQAAglgNgfQgMgggVgWQgWgWgbgNQgegMgjAAQgjAAgdAMgALSAeIArhAQAVgiAWglIhciUQgmg9gRghIgRgfQgGgMAAgNQAAgNAHgLQAIgLAVAAQAMAAAJACIAPAGIAZAvIAkBAIApBHIApBEQAdg2Acg2IA1hqIAJgSQAFgJAHgFQAGgGAJgDQAIgCANAAQASAAAKAGIAQAJQgeBAgeA6QgfA6gfA3Ig/BuQggA2gjA1gEAgKAAUIAAmcQAAgtAxAAIEBAAQAoAAAAAkQAAANgEAKIgGAOIj/AAIAABzIDYAAQAnAAAAAkQAAANgEALQgDAKgDADIj1AAIAAB9IEFAAIAABHgAd0AUIgiguIglgzIgogxIgmgsIgTACIgVABIggAAIAAC7IhPAAIAAmkQAAgkAoAAQAOAAALADIAOAEIAAC/IAcAAQAcAAASgJQATgJAPgSQAegiARgeIAggyQAOgXAPgMQAPgNAXAAQASAAAKAFQALAFAIAGIg1BQQgdAsghAuQgKAOgKAMQgKALgMAJIArAyIAsA5IArA9IAnA4gAWYAUIAAmBIjsAAIAAGBIhPAAIAAmcQAAgtAwAAIEpAAQAxAAAAAtIAAGcgAIRAUIghguIgmgzIgngxIgngsIgTACIgUABIggAAIAAC7IhPAAIAAmkQAAgkAnAAQAOAAALADIAPAEIAAC/IAbAAQAcAAATgJQASgJAQgSQAdgiASgeIAggyQAOgXAPgMQAOgNAYAAQASAAAKAFQAKAFAJAGIg1BQQgeAsghAuQgKAOgKAMQgKALgLAJIAqAyIAsA5IArA9IAnA4gAntAUIAAmBIjsAAIAAGBIhPAAIAAmcQAAgtAwAAIEpAAQAxAAAAAtIAAGcgAyAAUIAAlRQgcAlggAuIg/BcIg9BaIg0BIIhQAAIAAmkQAAgTALgJQALgJATAAQANAAAKADIAPAFIAAFFIBfiGIBiiIIARgXQAJgLAKgJQAKgJAMgEQAMgGAPAAQANAAAJACQAKACAFADIAAHBgA93AUIAAmeQAAgVAKgJQALgKAPgDIAngEQAdgCA0gBQBrAAA0AqQA1AqAABHQAAAhgMAcQgLAcgYAWQgYAUgnAMQgnAMg3AAIgdgBIgagCIgVgDIgLgBIAAChgA8Rl3QgTACgGABIAACjIAbAEQAVADAhAAQAlAAAZgHQAZgGAOgNQAPgLAGgQQAGgQAAgSQAAgRgFgQQgGgPgPgMQgOgMgagIQgagHgoAAQggAAgUABgEggoAAUIAAmBIjrAAIAAGBIhQAAIAAmcQAAgtAwAAIEqAAQAwAAAAAtIAAGcg");
	this.shape.setTransform(752.7,163.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(512.3,118.7,480.9,90.1);


(lib.txt1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHNEbQgsgQgigeQgigfgUgsQgTgtAAg6QAAg6ATgsQATgtAhgfQAhgfAsgRQAtgQAyAAQAwAAAfAIQAfAIASALQARAMAHANQAHAMAAAIQAAAJgDAIQgEAIgFAGIgLALIgJAHQgHgIgLgIQgMgJgQgHQgQgIgUgFQgVgFgXAAQgiAAgeAMQgdAMgWAWQgVAXgMAgQgNAdAAApQAAAoANAgQANAfAXAVQAXAVAfALQAfAKAjAAQAqAAAfgKQAegLAPgKIAjA9IABAAIgVANQgNAHgUAHQgTAHgbAFQgbAEgiAAQgyAAgsgPgAStEaQgPgPAAgUQAAgVAPgPQAPgOAVAAQAVAAAPAOQAPAPAAAVQAAAUgPAPQgPAPgVAAQgVAAgPgPgAgZEkIgzgCIgkgCIgTgCIAAmeQAAgVALgKQALgKAOgCQANgDAegCQAegCA2AAQA9AAAoALQAnAKAWASQAXASAJAXQAIAXAAAaQAAAVgGARQgFAOgJAMQgIAMgLAIQgKAJgKAEQAiAMAVAcQAVAbAAArQAAAcgJAZQgIAYgYATQgYASgrALQgqAKhDAAIg7gBgAg1DbIAeADQAXADArAAQAjAAAYgFQAYgEAPgJQAQgJAGgNQAGgNAAgSQAAgPgEgLQgEgNgLgJQgKgJgRgFQgRgFgaAAIiFAAgAgWhsQgZACgGABIAAB7IB7AAQAXAAAQgGQAQgEAKgIQAKgHAFgMQAEgMAAgNQAAgOgGgNQgGgMgNgJQgNgIgWgFQgXgGggAAQgnAAgWADgAMHEeIAAmcQAAgtAxAAIEBAAQAoAAAAAkQAAANgEAKIgGAOIj/AAIAABxIDYAAQAnAAAAAkQAAANgEAKQgDALgDADIj1AAIAAB9IEFAAIAABJgAm3EeIgJgXIgMgfIgNgjIgMgfIjhAAIgaBEIgTA0IhQAAQAQgtAVg0IAshqIAvhtIAxhuQAMgbAPgKQAPgKAYAAIARABIAPAFIAKAFIAFADQALATARAlIAlBTIApBdIAmBfIAfBPIATAxgApng8IgWAzIgXA0IgVA1ICpAAIgVg3IgYg4IgWg0IgRgjIgTAqgAvHEeIAAjKIjsAAIAADKIhQAAIAAmkQAAgTALgJQAMgJAUAAQAMAAALADIAOAFIAACuIDsAAIAAiRQAAgTALgJQALgJATAAQAOAAAKADIAPAFIAAHBgASqCLIAAkTQAAgSALgJQAMgIASAAQAMAAAKADIAOAFIAAEugAPgjjQgNgNAAgPQAAgQANgNQANgNASAAQARAAANANQANANAAAQQAAAPgNANQgNANgRAAQgSAAgNgNgANbjZQgIgEgGgGQgGgFgEgIQgDgHAAgIQAAgQANgNQANgNARAAQASAAANANQANANAAAQQAAAPgNANQgNANgSAAQgIAAgIgDg");
	this.shape.setTransform(711.6,157.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(583.2,127.3,256.9,59.8);


(lib.Tween1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.fon_element();
	this.instance.setTransform(-556,-556);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-556,-556,1112,1112);


(lib.Mustache_an = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJJK5QmGhxjDkaQjDEamGBxQkfBUm7AAQiXAAingpQi8guighXQmPjbhjmJQgxjJBKixQA6iNB9hqQBjhVBRgWQAhgJAGALQAHAMgdAdQg8A9gTBOQgTBPAcBNQBCCyEOBBQCRAjB+hHQBUgwCFiNQCdimBQg9QCah3CvghQFOhAD1CVQB6BKA1BXIArg1QA7g+BMguQD1iVFNBAQCwAhCaB3QBQA9CcCmQCGCOBTAvQB+BICRgjQEOhBBDiyQAchNgUhPQgThOg8g9QgcgdAGgMQAGgLAhAJQBRAVBjBVQB9BrA6CMQBJCygyDIQhiGJmPDbQigBXi8AuQinApiYAAQm7AAkfhUg");
	this.shape.setTransform(144.9,67.2,0.473,0.473);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(26.7,30.3,236.5,73.9);


(lib.love_an = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A0rLtIg2guQhLhCARgwQAWg+A2ADQAVACARAMQAQALADAOQABgOAQgNQAPgMAVgDQA0gIAaA9QATAuhGBHIgzAyQgWAXgCAMQgCgMgYgVgArWB1Qi1jBhXjQQAJAWAbAVQA2ApBbADQA1ACBLgbQApgOBjgtQDBhYBnAAQB0AACGBMQBMArA6AyQA9g0BKgpQCIhMB0AAQBmAADCBYQBiAtAqAOQBKAbA1gCQBcgDA1gpQAcgVAJgWQhXDQi1DBQlqGHn2AAQnzAAlqmHgApKg2QA5AiBMAbQDxBbFJAAQEpAAEJhYQCFgpBJgsQozB+oSg1QkKgciag1gAUik9IgpglQg5g0AOglQASgwAqAEQAoADAEAcQADgVAWgIQAHgCAKgBQAigEATAhIAHAOQAIAUgPAbQgLAUgYAXIgjAgIgGAGQgTASAAAKQgBgKgTgSgAOmm+Qg0gugbgaQhvhmAbhIQAjheBSAIQBNAHAHA1QAIg1BKgJQBQgJAlBdQAbBIhtBoIhQBJQglAkAAATQgBgTglgjg");
	this.shape.setTransform(143.9,78.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,287.9,156.5);


(lib.final_text = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aa8DYIAAhYIkOAAIAABYIgiAAIAAhjQAAgIAGgGQAFgFAMgBIANAAIALgsIANg1IAMg0IAKgqQAHgiAOgWQAMgXASgOQARgMAWgHQAWgFAbAAQAZAAAQACIAWACQAUADAAARIAAEcIALAAQAMABAFAFQAGAGAAAIIAABjgAZDiyQgQAEgNAKQgMALgJASQgJATgIAbIgKApIgMA0IgMA1IgKAoIDGAAIAAkTIgTgDQgNgCgQABQgXAAgQAEgAIoB8QgggLgZgXQgYgXgPggQgOghAAgnQAAgqAOghQAPghAXgXQAYgXAhgMQAfgMAkgBQAkAAAaAJQAaAIALAJQAIAFACAEQACAFAAAFQAAAGgEAHQgFAFgFAEQgGgHgJgGQgJgHgNgEQgNgFgPgEQgRgDgQAAQgdAAgZAKQgaAKgSATQgTAUgLAbQgLAbABAjQgBAjAMAZQAMAbASASQAUATAaAJQAbAJAdAAQARABAPgDQAQgDAMgDQAMgEAJgEIAOgIIAPAbIgQAIQgJAGgOAEQgMAEgTADQgSADgYABQgkAAgggNgA+WB7QgggNgYgYQgXgXgOghQgNgfAAgmQAAgmANghQAOggAXgXQAYgYAggNQAggOAmAAQAmAAAgAOQAhANAXAYQAZAXANAgQAOAhAAAmQAAAmgOAfQgNAhgZAXQgXAYghANQggAOgmAAQgmAAgggOgA+HivQgZALgTATQgTAUgLAaQgKAcAAAgQAAAhAKAYQALAbATAVQATATAZALQAZALAegBQAeABAagLQAagLASgTQAUgVAKgbQALgYAAghQAAgggLgcQgKgagUgUQgSgTgagLQgagLgeABQgegBgZALgEAhxACGIAfgvIAegwIgnhAIgjg2IgbgtIgWgnIgJgSQgDgHAAgFQAAgEADgFQACgEAKgBIAHABIAHABIAMAXIATAiIAXAnIAZAqIAZAoIAXAhQAZgqAYguIAyhhIAFgLQADgGAEgDQAEgEAFgCQAFgCAIAAIAIABIAIADIgwBfIguBVQgWAmgYAnQgYAngbApgAznCGIAegvIAfgwIgohAIgig2IgcgtIgVgnIgJgSQgDgHgBgFQAAgEADgFQADgEAKgBIAHABIAHABIALAXIATAiIAYAnIAYAqIAZAoIAXAhQAZgqAZguIAxhhIAGgLQADgGADgDQAEgEAFgCQAFgCAJAAIAIABIAIADIgxBfIgtBVQgXAmgXAnQgYAngbApgABQCDIgdgBIgWgBIgMgCIAAk8QAAgIAFgEQADgGAKAAQAFABAEABQAEABADACIAABtIAMgBIARgCIATgBIARAAIAiACQASABARADQASAFAQAHQAQAIAMAMQAMAMAHATQAHATAAAXQAAA7goAeQgnAehRgBIghgBgABQhCQgSABgLACIAACjIAcACIAqABQAaAAAVgFQAWgEAPgKQAPgLAJgQQAHgSABgZQAAgRgGgOQgFgPgKgIQgJgKgMgFQgNgGgNgCQgNgDgNAAIgYgBIgnABgAf1CAQgNgTgRgVIghgoIgkgnIghggQgPADgTAAIgfAAIAACUIgiAAIAAk9QAAgIAEgEQAEgGAKAAIAJABIAHADIAACaIAdAAQAMAAAKgCQAKgCAHgDQAIgEAIgHQAHgIAJgKIAVgbIATgaIAQgWIAKgNIASgYQAKgKANAAQAGAAAFACIAIAGIgvA/Ig0BCQgIALgIAJQgJAIgIAGIAjAkIAlAnIAkAsQARAVAQAYgAU9CAIAAklQg1BJg0BKIhoCSIgnAAIAAk9QAAgIADgEQAFgGAJAAIAKABIAGADIAAEdIBiiHIBjiKQAHgIAHgEQAIgDAIgBQAIABAGABQAGABACACIAAFKgAPyCAQgNgTgRgVIgigoIgjgnIgiggQgOADgUAAIgfAAIAACUIghAAIAAk9QAAgIADgEQAFgGAJAAIAKABIAGADIAACaIAeAAQAMAAAJgCQAKgCAIgDQAIgEAHgHQAIgIAJgKIAVgbIATgaIAQgWIAJgNIATgYQAJgKANAAQAHAAAFACIAIAGIgwA/IgzBCQgIALgIAJQgJAIgJAGIAjAkIAlAnIAkAsQASAVAQAYgAjGCAIAAkwIh1AAQgHgBgEgEQgFgDAAgIQAAgFACgEIADgGIEhAAQAHABAEADQAFAEAAAIQAAAFgBAEIgEAGIiJAAIAAEwgAmVCAIAAklQg1BJg1BKIhnCSIgoAAIAAk9QAAgIAEgEQAEgGAJAAIAKABIAGADIAAEdIBiiHIBkiKQAHgIAHgEQAHgDAIgBQAJABAGABQAFABADACIAAFKgAr8CAIAAiCQgQACgVADQgUACgfABQgdAAgbgGQgagEgUgOQgUgNgLgVQgMgWAAgeIAAhVQAAgIAEgEQAFgGAJAAIAJABIAHADIAABjQAAAoAbAUQAbAVA6AAIAeAAIAWgCIASgDIARgEIAAidQAAgIAFgEQAEgGAJAAIAJABIAHADIAAFLgA1+CAIAAkyIgTgDQgOgCgQABQgWAAgRAEQgPAEgNAKQgMALgJASQgJATgIAbIgQBAQgGAegJAfIgHAXIgJAaQgEAMgHAKQgFALgHAKIgnAAQAbglAOgzQAKgiAHggIAQhEQAIgiANgWQANgXASgOQARgMAVgHQAXgFAaAAQAaAAAQACIAVACQAVADAAARIAAE7gEghfACAIAAkxIjXAAIAAExIgiAAIAAk7QABgJAEgFQAGgFAMgBIDuAAQALABAGAFQAFAFABAJIAAE7g");
	this.shape.setTransform(245.1,53.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(5.8,31.7,478.6,43.4);


(lib.f = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.fon_element();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1112,1112);


(lib.dp = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.dark_panel();
	this.instance.setTransform(448,102.1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(448,102.1,722,123);


(lib.background = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("Egq9AfPMAAAg+eMBV6AAAMAAAA+eg");
	this.shape.setTransform(275,200);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,550,400);


(lib.Baby_an = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGJNoQgvgPgmgeQgQAFgRAAIokAAQgRAAgQgFQgmAegvAPQgvAQgzAAQhLgBhIgfQhIgfg6g5Qgygzgeg+Qgfg9gHhCQgIhHAVhBQAVhAAvgwQApgoA2gWQA2gWA+AAIANAAIhZgjQg0gWgogoQgogngWg1QgWgyAAg4QAAg4AWg1QAhhPBIgwQBHgvBXAAQAuAAAtAOQgCgYAAgWQAAhgAlhYQAkhVBBhBQBChBBVgkQBXglBeAAQBgAABYAlQBVAkBBBBQBBBBAkBVQAlBXAABgQAAAYgCAWQAtgPAvAAQBWAABIAwQBHAvAhBQQAVA0AAA4QAAA3gVAyQgWA0gnAmQgmAmg1AWIhlArIAYgBQA9AAA2AWQA2AWApAoQAtAuAVA+QAVA9gFBEQgFBDgeBAQgfBCg1A2Qg6A5hIAfQhIAfhLABQgzAAgvgQgAHsFKQg1AYgrAqQhMBMgKBhQgLBhA9A8QAZAZAjAOQAhANAmAAQA0gBAzgWQA1gXArgqQBLhNALhgQALhgg9g+QgZgZgjgNQghgNgmAAQgzAAg0AWgAqYFBQgiANgaAZQg9A+ALBgQALBgBMBNQArAqA1AXQAzAWAzABQAmAAAigNQAigOAagZQA9g8gLhhQgLhhhMhMQgqgqg1gYQg0gWgzAAQgmAAgiANgAEULRQglhRAhh4QAgh1BOhOQAEgEAFgCQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAIgGgnIsGAAIgFAnQAAAAAAABQAAAAAAAAQABAAAAABQABAAABABQAEACAFAEQBNBOAhB1QAhB4glBRIIlAAIAAAAgAGFDeIAAgdIABgmIDuhmQBDgcAag9QAOggAAggQAAgigOggQgUgxgrgcQgsgdg0AAQgjAAgeAOIhrAmQg5BghsBEQhyBGhuAAQhrAAhzhGQhrhEg6hgIhqgmQgggNgiAAQg1AAgsAdQgrAdgUAxQgOAfAAAjQAAAiAOAgQANAgAYAWQAYAYAgANIDuBgQgBAFABAhIABAdIMHAAIAAAAgAiKrsQhBAcgyAyQgyAygbBBQgdBDAABKQAABIAdBEQAbBAAyAyQAyAyBBAcQBCAcBIAAQBKAABDgcQBAgbAygzQAygxAchBQAchDAAhJQAAhKgchDQgchBgygyQgygyhAgcQhDgbhKAAQhHAAhDAbgAiFi+Qg3gkgggyIG7AAQgfAxg4AlQhDAshFAAQhDAAhCgsg");
	this.shape.setTransform(145.5,61);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(56.8,-27.8,177.6,177.6);


(lib.arr_an = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhmB8ICxh8Iixh8IAAgyIC8CLQAKAGADAKQAEAJAAAKQAAAJgCAIQgBAGgDAGIjHCSg");
	this.shape.setTransform(10.4,17.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,20.7,35.1);


(lib._5w = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaMyQgngDgkgSQgkgTgdggQgdgfgPgqQgPgqACgrQACgqAQglQAQglAfgdQAegdApgPQAogPApAEQAqADAkASQAkASAcAgQAdAfAPArQAPAqgCAqQgBAqgRAmQgQAlgeAcQgeAcgqAPQgkANgjAAIgMAAgAAAHyQgWAIgQAOQgRAQgJATQgKATgBAXQgCAWAIAWQAIAWAQAQQAPARATAJQASAJAWAAQAXACAWgIQAWgIARgQQARgPAJgTQAJgTABgWQACgXgIgWQgIgWgPgQQgQgQgTgJQgTgKgWgBIgDAAQgWAAgTAIgAklD9IgnhsINQCWQATADAQAHQAQAHAKAcQAIAXgDASQgCASgDAGgADPCoQgqgDglgSQgjgSgdggQgcgfgPgrQgQgoACgqQACgqAQgmQARglAegcQAegdApgPQAqgPApADQAqADAkASQAlATAcAfQAcAfAPAqQAPArgBAqQgCApgRAlQgQAlgeAcQgeAdgqAPQgiANgjAAIgNgBgACyiWQgWAIgQAPQgRAPgJATQgJATgCAXQgCAWAIAWQAIAVAQAQQAQAQATAJQATAJAXABQAWABAWgIQAWgIARgPQARgPAJgUQAJgRACgWQABgWgIgXQgIgWgPgQQgQgQgTgJQgTgJgXgBIgFAAQgUAAgUAHgAk9i7QgxgDgrgYQgrgZgjgtQgkgugYhDQgSgygHgrQgIgrgBgjQgBghACgXQADgYACgIIBqANQgEAfACA1QACA2AWA+QAfBXAxAbQAwAaA0gSQAagKATgRQATgSAKgbQAJgbgEgnQgCgngTgzQgIgWgKgXIgWgsIgWgnIgUgfIE9hoQBGgWAZBIIBrEpQAWA8g0ATQgTAHgRgBQgRgBgHgBIhvk2IikA2IAUAqQAMAbAMAhQAaBHgBA4QgBA3gTAqQgUApgiAbQgjAcgqAOQgrAQgqAAIgNgBg");
	this.shape.setTransform(108.6,116.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(50.3,34.3,116.6,163.8);


(lib._5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED357B").s().p("ApCFiQgmgGgdgJQgdgJgTgKQgTgIgGgFIArhWQAZAOAtAOQAuAPA7AAQBSAAAmgiQAlggAAgxQAAgZgJgWQgJgVgUgQQgUgQgigJQgigJgxAAQgVAAgWACIgrAFIgoAHIggAHIAJkqQAChCBFABIEbAAQA5AAAAAwQAAATgHAOIgIATIknAAIgECdIApgEQAagDAfAAQBEAAAvASQAvASAdAbQAcAcANAlQAMAmAAAoQAAAvgRAoQgSAoghAdQgiAdgwAQQgyAPhAABQgvAAgngIgAHDFYQgjgPgagZQgagYgPgiQgPgjAAgnQAAgnAPgiQAPgjAagYQAagZAjgOQAjgNApAAQAoAAAjANQAjAOAbAZQAaAYAPAjQAOAiAAAnQAAAngOAjQgPAigaAYQgbAZgjAPQgjAOgoAAQgpAAgjgOgAHnBPQgSAHgOAPQgNAMgIATQgHATAAAVQAAAVAHATQAIASANAOQAOAOASAIQATAIAVAAQAVAAASgIQASgIANgOQAOgOAIgSQAIgTAAgVQAAgVgIgTQgIgTgOgMQgNgPgSgHQgSgJgVAAQgVAAgTAJgAAdFZIF/qcQAJgQALgKQALgMAaAAQAWAAAPAIQAOAHAEAFImIKugAgngCQgjgOgbgZQgagagPgiQgPgiAAgnQAAgnAPgjQAPghAagaQAbgZAjgOQAjgPAmAAQAoAAAkAPQAjAOAaAZQAaAaAPAhQAPAjAAAnQAAAngPAiQgPAigaAaQgaAZgjAOQgkAMgoAAQgmAAgjgMgAgDkMQgTAJgNANQgNANgIATQgIASAAAWQAAAVAIASQAIAUANANQANANATAIQAQAIAVAAQAVAAASgIQATgIANgNQANgNAIgUQAIgSAAgVQAAgWgIgSQgIgTgNgNQgNgNgTgJQgSgIgVAAQgVAAgQAIg");
	this.shape.setTransform(75.3,93.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.4,57,144,72.4);


(lib._4 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED357B").s().p("AHSFZQgjgOgagZQgagYgPgjQgPgiAAgoQAAgnAPgiQAPgiAagYQAagaAjgOQAjgMApAAQAoAAAjAMQAjAOAbAaQAaAYAPAiQAOAiAAAnQAAAogOAiQgPAjgaAYQgbAZgjAOQgjAPgoAAQgpAAgjgPgAH2BRQgSAHgOAOQgNANgIATQgHATAAAUQAAAVAHAUQAIASANANQAOAOASAJQATAHAVABQAVgBASgHQASgJANgOQAOgNAIgSQAIgUAAgVQAAgUgIgTQgIgTgOgNQgNgOgSgHQgSgJgVAAQgVAAgTAJgAAsFaIF/qcQAJgPALgLQALgLAaAAQAWAAAPAIQAOAHAEAFImIKtgAmKFaIAAiRIi5AAQhKAAgogYQgogaAAg4QAAgrASgtQATgtAegsQAegtAngqQAogpAqgfQAqgfApgUQAqgSAjAAQAiAAAQAHIAVAJIAAGLIAgAAQA5AAAAAxQAAASgGAOIgJATIhKAAIAACRgAnTiXQgoAgghAmQgiAmgWAnQgXAmAAAeQAAAYARAGQASAHAcAAICiAAIAAkuQgiASgnAggAgYAAQgjgPgbgZQgagZgPgiQgPgjAAgmQAAgoAPgjQAPghAagZQAbgZAjgPQAhgOAoAAQAoAAAkAOQAjAPAaAZQAaAZAPAhQAPAjAAAoQAAAmgPAjQgPAigaAZQgaAZgjAPQgkAMgogBQgoABghgMgAAKkLQgRAJgNANQgNAOgIASQgIATAAAWQAAAUAIATQAIATANAOQANANARAIQASAIAVAAQAVAAASgIQATgIANgNQANgOAIgTQAIgTAAgUQAAgWgIgTQgIgSgNgOQgNgNgTgJQgSgHgVgBQgVABgSAHg");
	this.shape.setTransform(78.9,93.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(5.5,57,147,72.1);


(lib._3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED357B").s().p("Ao6FiQgpgIgggKQgggKgWgLQgWgLgKgHIAwhWQAMAJARAIQATAJAYAHQAYAIAdAFQAeAGAhAAQBHAAAmgbQAlgdAAgxQAAgygogYQgogYhGAAIg8AAQgDgFgGgPQgGgPAAgSQAAgwA9ABIATAAQBCAAAjgbQAigbAAgsQAAgrgigbQghgahEAAQgnAAgbAJQgcALgTANQgTANgMAOQgKAOgDAIQgZgEgRgRQgSgQAAgWQAAgOAEgMQAFgMAMgOQAHgGAPgMQAOgLAZgKQAZgLAjgIQAigIAvAAQBAAAAuAQQAuAPAeAZQAdAYAPAhQAOAgAAAiQAAAdgKAZQgJAZgPATQgQAUgTAPQgUAPgUAHQBAAVAcArQAcAsAAAzQAAAqgRAmQgSAkghAaQggAbguAOQguAPg5AAQgwgBgqgHgAHOFYQgjgPgbgZQgagYgPgiQgPgjAAgnQAAgnAPgiQAPgjAagYQAbgZAjgOQAjgNAoAAQApAAAiANQAjAOAbAZQAaAYAPAjQAPAiAAAnQAAAngPAjQgPAigaAYQgbAZgjAPQgiAOgpAAQgoAAgjgOgAHyBPQgSAHgOAPQgOAMgHATQgIATAAAVQAAAVAIATQAHASAOAOQAOAOASAIQASAIAVAAQAVAAATgIQASgIANgOQAOgOAHgSQAIgTAAgVQAAgVgIgTQgHgTgOgMQgNgPgSgHQgTgJgVAAQgVAAgSAJgAAoFZIF/qcQAIgQAMgKQAKgMAbAAQAWAAAOAIQAOAHAEAFImHKugAgdgCQgjgOgagZQgbgagPgiQgPgiAAgnQAAgnAPgjQAPghAbgaQAagZAjgOQAhgPApAAQAoAAAjAPQAjAOAaAZQAbAaAPAhQAPAjAAAnQAAAngPAiQgPAigbAaQgaAZgjAOQgjAMgoAAQgpAAghgMgAAFkMQgQAJgOANQgNANgIATQgHASAAAWQAAAVAHASQAIAUANANQAOANAQAIQASAIAWAAQAVAAASgIQASgIAOgNQANgNAIgUQAHgSAAgVQAAgWgHgSQgIgTgNgNQgOgNgSgJQgSgIgVAAQgWAAgSAIg");
	this.shape.setTransform(76.1,93.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.1,57,146.1,72.4);


(lib._2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED357B").s().p("AG9FZQgjgOgagZQgbgYgPgjQgOgiAAgoQAAgnAOgiQAPgiAbgYQAagaAjgOQAjgMAoAAQApAAAiAMQAjAOAbAaQAbAYAPAiQAOAiAAAnQAAAogOAiQgPAjgbAYQgbAZgjAOQgiAPgpAAQgoAAgjgPgAHhBRQgSAHgOAOQgNANgIATQgHATgBAUQABAVAHAUQAIASANANQAOAOASAJQATAHAUABQAWgBASgHQASgJANgOQAOgNAHgSQAJgUgBgVQABgUgJgTQgHgTgOgNQgNgOgSgHQgSgJgWAAQgUAAgTAJgAAXFaIF/qcQAJgPALgLQAKgLAbAAQAWAAAPAIQANAHAFAFImIKtgArIFaIAAhgIArgeIBBguIBGgzQAigbAXgWQA3gxAfgpQAdgsAAg2QAAgXgIgVQgJgUgQgRQgRgQgbgKQgZgKglAAQgkABgbAKQgaAKgSAPQgSAPgKAPQgKAPgDAJQgJgCgKgFQgLgFgIgHQgJgIgHgKQgGgKAAgNQAAgOAFgNQAFgMAIgLQAFgHAOgNQAOgNAZgMQAXgNAkgJQAigKAxAAQA8AAAuAQQAuAQAgAcQAfAbAPAlQAQAmABArQgBAhgHAeQgIAdgMAYQgNAVgQAVQgPAVgRARQgQATgeAaQgcAZgfAZIg6AuIgpAfIEpAAIAABlgAguAAQgjgPgagZQgagZgPgiQgQgjABgmQgBgoAQgjQAPghAagZQAagZAjgPQAkgOAmAAQAoAAAkAOQAiAPAbAZQAaAZAPAhQAPAjAAAoQAAAmgPAjQgPAigaAZQgbAZgiAPQgkAMgogBQgmABgkgMgAgKkLQgSAJgOANQgNAOgIASQgHATAAAWQAAAUAHATQAIATANAOQAOANASAIQAQAIAWAAQAVAAASgIQATgIANgNQANgOAIgTQAIgTgBgUQABgWgIgTQgIgSgNgOQgNgNgTgJQgSgHgVgBQgWABgQAHg");
	this.shape.setTransform(74.9,93.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.6,57,142.7,72.1);


(lib._1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED357B").s().p("AGSFZQgjgOgbgZQgagYgPgjQgPgiAAgoQAAgnAPgiQAPgiAagYQAbgaAjgOQAjgMAoAAQApAAAiAMQAjAOAbAaQAaAYAPAiQAPAiAAAnQAAAogPAiQgPAjgaAYQgbAZgjAOQgiAPgpAAQgoAAgjgPgAG2BRQgSAHgOAOQgOANgHATQgIATAAAUQAAAVAIAUQAHASAOANQAOAOASAJQASAHAVABQAVgBATgHQASgJANgOQAOgNAHgSQAIgUAAgVQAAgUgIgTQgHgTgOgNQgNgOgSgHQgTgJgVAAQgVAAgSAJgAgSFaIF9qcQAIgPAMgLQAKgLAbAAQAWAAAOAIQAOAHAEAFImHKtgAnSFaIAAoOIiZBuIgOgIQgJgEgIgIQgIgHgGgKQgFgKAAgMQAAgVALgPQAKgOAYgQIB0hQQAXgQATgJQAUgKAdAAQAYAAARAHQARAHAEADIAAJ/gAhZAAQgjgPgagZQgbgZgPgiQgPgjAAgmQAAgoAPgjQAPghAbgZQAagZAjgPQAjgOApAAQAmAAAjAOQAjAPAaAZQAbAZAPAhQAPAjAAAoQAAAmgPAjQgPAigbAZQgaAZgjAPQgjAMgmgBQgpABgjgMgAg1kLQgSAJgOANQgNAOgIASQgHATAAAWQAAAUAHATQAIATANAOQAOANASAIQASAIAWAAQATAAASgIQASgIAOgNQANgOAIgTQAHgTAAgUQAAgWgHgTQgIgSgNgOQgOgNgSgJQgSgHgTgBQgWABgSAHg");
	this.shape.setTransform(70.6,93.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.6,57,134,72.1);


(lib.price = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 5
	this.instance = new lib._5("synched",0);
	this.instance.setTransform(119.3,88.5,1,1,0,0,0,71.3,85.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(127).to({_off:false},0).wait(1).to({regX:75.3,regY:93.2,x:123.3,y:96.4,alpha:0.008},0).wait(1).to({y:97,alpha:0.033},0).wait(1).to({y:97.9,alpha:0.074},0).wait(1).to({y:99.2,alpha:0.132},0).wait(1).to({y:101,alpha:0.207},0).wait(1).to({y:103,alpha:0.298},0).wait(1).to({y:105.5,alpha:0.405},0).wait(1).to({y:108.4,alpha:0.529},0).wait(1).to({y:111.6,alpha:0.669},0).wait(1).to({y:115.2,alpha:0.826},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:111.5,alpha:1},0).wait(1).to({regX:75.3,regY:93.2,x:123.3,y:114.2},0).wait(1).to({y:111.2},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:102.5},0).wait(1).to({regX:75.3,regY:93.2,x:123.3,y:112.5},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:105.5},0).wait(1));

	// 4
	this.instance_1 = new lib._4("synched",0);
	this.instance_1.setTransform(119.3,88.5,1,1,0,0,0,71.3,85.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(92).to({_off:false},0).wait(1).to({regX:78.9,regY:93,x:126.9,y:96.2,alpha:0.008},0).wait(1).to({y:96.8,alpha:0.033},0).wait(1).to({y:97.7,alpha:0.074},0).wait(1).to({y:99,alpha:0.132},0).wait(1).to({y:100.8,alpha:0.207},0).wait(1).to({y:102.8,alpha:0.298},0).wait(1).to({y:105.3,alpha:0.405},0).wait(1).to({y:108.2,alpha:0.529},0).wait(1).to({y:111.4,alpha:0.669},0).wait(1).to({y:115,alpha:0.826},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:111.5,alpha:1},0).wait(1).to({regX:78.9,regY:93,x:126.9,y:114},0).wait(1).to({y:111},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:102.5},0).wait(1).to({regX:78.9,regY:93,x:126.9,y:112.3},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:105.5},0).wait(14).to({y:105.7,alpha:0.988},0).to({y:130.5,alpha:0},5).to({_off:true},1).wait(16));

	// 3
	this.instance_2 = new lib._3("synched",0);
	this.instance_2.setTransform(119.3,88.5,1,1,0,0,0,71.3,85.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(57).to({_off:false},0).wait(1).to({regX:76.1,regY:93.2,x:124.1,y:96.4,alpha:0.008},0).wait(1).to({y:97,alpha:0.033},0).wait(1).to({y:97.9,alpha:0.074},0).wait(1).to({y:99.2,alpha:0.132},0).wait(1).to({y:101,alpha:0.207},0).wait(1).to({y:103,alpha:0.298},0).wait(1).to({y:105.5,alpha:0.405},0).wait(1).to({y:108.4,alpha:0.529},0).wait(1).to({y:111.6,alpha:0.669},0).wait(1).to({y:115.2,alpha:0.826},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:111.5,alpha:1},0).wait(1).to({regX:76.1,regY:93.2,x:124.1,y:114.2},0).wait(1).to({y:111.2},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:102.5},0).wait(1).to({regX:76.1,regY:93.2,x:124.1,y:112.5},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:105.5},0).wait(14).to({y:105.7,alpha:0.988},0).to({y:130.5,alpha:0},5).to({_off:true},1).wait(51));

	// 2
	this.instance_3 = new lib._2("synched",0);
	this.instance_3.setTransform(119.3,88.5,1,1,0,0,0,71.3,85.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(22).to({_off:false},0).wait(1).to({regX:74.9,regY:93,x:122.9,y:96.2,alpha:0.008},0).wait(1).to({y:96.8,alpha:0.033},0).wait(1).to({y:97.7,alpha:0.074},0).wait(1).to({y:99,alpha:0.132},0).wait(1).to({y:100.8,alpha:0.207},0).wait(1).to({y:102.8,alpha:0.298},0).wait(1).to({y:105.3,alpha:0.405},0).wait(1).to({y:108.2,alpha:0.529},0).wait(1).to({y:111.4,alpha:0.669},0).wait(1).to({y:115,alpha:0.826},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:111.5,alpha:1},0).wait(1).to({regX:74.9,regY:93,x:122.9,y:114},0).wait(1).to({y:111},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:102.5},0).wait(1).to({regX:74.9,regY:93,x:122.9,y:112.3},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:105.5},0).wait(14).to({y:105.7,alpha:0.988},0).to({y:130.5,alpha:0},5).to({_off:true},16).wait(71));

	// 1
	this.instance_4 = new lib._1("synched",0);
	this.instance_4.setTransform(119.3,105.5,1,1,0,0,0,71.3,85.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(16).to({startPosition:0},0).wait(1).to({regX:70.6,regY:93,x:118.6,y:114,alpha:0.96},0).wait(1).to({y:117,alpha:0.84},0).wait(1).to({y:122,alpha:0.64},0).wait(1).to({y:129,alpha:0.36},0).wait(1).to({regX:71.3,regY:85.5,x:119.3,y:130.5,alpha:0},0).to({_off:true},1).wait(122));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(51.6,77,134.1,72.1);


(lib.Mustache = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Mustache_an();
	this.instance.setTransform(143.9,78.3,1,1,0,0,0,143.9,78.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(26.7,30.3,236.5,73.9);


(lib.love = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.love_an();
	this.instance.setTransform(143.9,78.3,1,1,0,0,0,143.9,78.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,287.9,156.5);


(lib.clouth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// price2
	this.instance = new lib._5w();
	this.instance.setTransform(553.7,570.8,1,1,0,0,0,118.8,112.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(155).to({_off:false},0).to({alpha:1},40).wait(305));

	// price
	this.instance_1 = new lib.price("synched",0,false);
	this.instance_1.setTransform(550.4,574.9,1.118,1.118,70.2,0,0,126.6,109.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(500));

	// fon
	this.instance_2 = new lib.fon_element();

	this.instance_3 = new lib.Tween1("synched",0);
	this.instance_3.setTransform(556,556);
	this.instance_3._off = true;

	this.instance_4 = new lib.f();
	this.instance_4.setTransform(556,556,1,1,0,0,0,556,556);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},155).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).wait(305));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(155).to({_off:false},0).wait(1).to({alpha:0.951},0).wait(1).to({alpha:0.902},0).wait(1).to({alpha:0.856},0).wait(1).to({alpha:0.81},0).wait(1).to({alpha:0.766},0).wait(1).to({alpha:0.723},0).wait(1).to({alpha:0.681},0).wait(1).to({alpha:0.64},0).wait(1).to({alpha:0.601},0).wait(1).to({alpha:0.563},0).wait(1).to({alpha:0.526},0).wait(1).to({alpha:0.49},0).wait(1).to({alpha:0.456},0).wait(1).to({alpha:0.423},0).wait(1).to({alpha:0.391},0).wait(1).to({alpha:0.36},0).wait(1).to({alpha:0.331},0).wait(1).to({alpha:0.303},0).wait(1).to({alpha:0.276},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.226},0).wait(1).to({alpha:0.203},0).wait(1).to({alpha:0.181},0).wait(1).to({alpha:0.16},0).wait(1).to({alpha:0.141},0).wait(1).to({alpha:0.123},0).wait(1).to({alpha:0.106},0).wait(1).to({alpha:0.09},0).wait(1).to({alpha:0.076},0).wait(1).to({alpha:0.063},0).wait(1).to({alpha:0.051},0).wait(1).to({alpha:0.04},0).wait(1).to({alpha:0.031},0).wait(1).to({alpha:0.023},0).wait(1).to({alpha:0.016},0).wait(1).to({alpha:0.01},0).wait(1).to({alpha:0.006},0).wait(1).to({alpha:0.003},0).wait(1).to({alpha:0.001},0).to({_off:true},1).wait(305));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1112,1112);


(lib.Baby = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Baby_an();
	this.instance.setTransform(143.9,78.3,1,1,0,0,0,143.9,78.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.8,-27.8,177.6,177.6);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.arr_an();
	this.instance.setTransform(10.4,17.6,1,1,0,0,0,10.4,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleY:0.11},5).to({scaleY:1},9).wait(1).to({scaleY:0.11},5).to({scaleY:1},13,cjs.Ease.get(1)).wait(22));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,20.7,35.1);


(lib.about = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// all7
	this.instance = new lib.Baby_an();
	this.instance.setTransform(14.6,159.6,0.482,0.482,-18.7,0,0,145.5,61);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(975).to({_off:false},0).to({alpha:1},99,cjs.Ease.get(1)).wait(26));

	// all6
	this.instance_1 = new lib.love_an();
	this.instance_1.setTransform(822.6,37.8,0.912,0.912,13.5,0,0,145.7,60.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(975).to({_off:false},0).to({regY:61.1,y:37.9,alpha:1},99,cjs.Ease.get(1)).wait(26));

	// all5
	this.instance_2 = new lib.love_an();
	this.instance_2.setTransform(229,258.2,0.711,0.711,-14.2,0,0,145.8,61);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(929).to({_off:false},0).to({regX:145.7,regY:61.1,x:228.9,alpha:1},99,cjs.Ease.get(1)).wait(72));

	// all4
	this.instance_3 = new lib.Mustache_an();
	this.instance_3.setTransform(202.6,86.8,0.619,0.619,17.5,0,0,145.7,60.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(883).to({_off:false},0).to({regX:145.6,regY:61,x:202.4,y:86.9,alpha:1},99,cjs.Ease.get(1)).wait(118));

	// all3
	this.instance_4 = new lib.Mustache_an();
	this.instance_4.setTransform(618.9,302.4,1.113,1.113,-12.3,0,0,145.6,60.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(835).to({_off:false},0).to({regY:61,x:619,y:302.5,alpha:1},99,cjs.Ease.get(1)).wait(166));

	// all2
	this.instance_5 = new lib.Baby_an();
	this.instance_5.setTransform(1047.9,229.5,0.693,0.693,-28,0,0,145.7,60.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(797).to({_off:false},0).to({regY:61,y:229.6,alpha:1},99,cjs.Ease.get(1)).wait(204));

	// all1
	this.instance_6 = new lib.Baby_an();
	this.instance_6.setTransform(1109.9,68.5,0.482,0.482,28.2,0,0,145.6,60.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(762).to({_off:false},0).to({alpha:1},99,cjs.Ease.get(1)).wait(239));

	// arr
	this.instance_7 = new lib.arrow();
	this.instance_7.setTransform(839.8,163.5,1,1,0,0,0,10.4,17.6);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(720).to({_off:false},0).to({alpha:1},28,cjs.Ease.get(1)).wait(352));

	// txt5
	this.instance_8 = new lib.final_text();
	this.instance_8.setTransform(569.6,157.7,1,1,0,0,0,243.5,44.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(720).to({_off:false},0).to({alpha:1},28).wait(352));

	// love copy 2
	this.instance_9 = new lib.Baby();
	this.instance_9.setTransform(291.1,173.5,1.139,1.139,0,0,0,143.9,78.4);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(617).to({_off:false},0).wait(1).to({regX:145.5,regY:61,x:292.9,y:153.6,alpha:0.001},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.003},0).wait(1).to({y:153.7,alpha:0.008},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.014},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.023},0).wait(1).to({scaleX:1.13,scaleY:1.13,y:153.8,alpha:0.035},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.05},0).wait(1).to({scaleX:1.13,scaleY:1.13,y:153.9,alpha:0.069},0).wait(1).to({scaleX:1.12,scaleY:1.12,alpha:0.093},0).wait(1).to({scaleX:1.12,scaleY:1.12,y:154,alpha:0.123},0).wait(1).to({scaleX:1.11,scaleY:1.11,y:154.2,alpha:0.161},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:154.3,alpha:0.21},0).wait(1).to({scaleX:1.09,scaleY:1.09,x:292.8,y:154.5,alpha:0.275},0).wait(1).to({scaleX:1.07,scaleY:1.07,y:154.8,alpha:0.369},0).wait(1).to({scaleX:1.04,scaleY:1.04,y:155.4,alpha:0.527},0).wait(1).to({regX:143.9,regY:78.4,scaleX:0.95,scaleY:0.95,x:291.1,y:173.5,alpha:1},0).to({scaleX:1.05,scaleY:1.05},3,cjs.Ease.get(1)).to({scaleX:0.98,scaleY:0.98},2,cjs.Ease.get(-0.5)).to({scaleX:1,scaleY:1},1).wait(49).to({scaleX:1.16,scaleY:1.16,alpha:0},18,cjs.Ease.get(-1)).wait(394));

	// txt3.1 copy 2
	this.instance_10 = new lib.txt33();
	this.instance_10.setTransform(178.1,-2.7,1,1,0,0,0,1.8,0.3);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(607).to({_off:false},0).to({x:1.8,y:0.3,alpha:1},22,cjs.Ease.get(1)).wait(59).to({x:172.8,alpha:0},18,cjs.Ease.get(-1)).wait(394));

	// love copy
	this.instance_11 = new lib.Mustache();
	this.instance_11.setTransform(291.1,173.5,1.139,1.139,0,0,0,143.9,78.4);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(522).to({_off:false},0).wait(1).to({regX:144.9,regY:67.2,x:292.2,y:160.7,alpha:0.001},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.003},0).wait(1).to({x:292.3,alpha:0.008},0).wait(1).to({scaleX:1.14,scaleY:1.14,x:292.2,alpha:0.014},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.023},0).wait(1).to({scaleX:1.13,scaleY:1.13,y:160.8,alpha:0.035},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.05},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.069},0).wait(1).to({scaleX:1.12,scaleY:1.12,y:160.9,alpha:0.093},0).wait(1).to({scaleX:1.12,scaleY:1.12,y:161,alpha:0.123},0).wait(1).to({scaleX:1.11,scaleY:1.11,alpha:0.161},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:161.1,alpha:0.21},0).wait(1).to({scaleX:1.09,scaleY:1.09,y:161.2,alpha:0.275},0).wait(1).to({scaleX:1.07,scaleY:1.07,y:161.5,alpha:0.369},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:292.1,y:161.8,alpha:0.527},0).wait(1).to({regX:143.9,regY:78.4,scaleX:0.95,scaleY:0.95,x:291.1,y:173.5,alpha:1},0).to({scaleX:1.05,scaleY:1.05},3,cjs.Ease.get(1)).to({scaleX:0.98,scaleY:0.98},2,cjs.Ease.get(-0.5)).to({scaleX:1,scaleY:1},1).wait(49).to({scaleX:1.16,scaleY:1.16,alpha:0},18,cjs.Ease.get(-1)).wait(489));

	// txt3.1 copy
	this.instance_12 = new lib.txt32();
	this.instance_12.setTransform(178.1,-2.7,1,1,0,0,0,1.8,0.3);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(512).to({_off:false},0).to({x:1.8,y:0.3,alpha:1},22,cjs.Ease.get(1)).wait(59).to({x:172.8,alpha:0},18,cjs.Ease.get(-1)).wait(489));

	// love
	this.instance_13 = new lib.love();
	this.instance_13.setTransform(291.1,173.5,1.139,1.139,0,0,0,143.9,78.4);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(427).to({_off:false},0).wait(1).to({regY:78.2,y:173.2,alpha:0.001},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.003},0).wait(1).to({alpha:0.008},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.014},0).wait(1).to({scaleX:1.14,scaleY:1.14,alpha:0.023},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.035},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.05},0).wait(1).to({scaleX:1.13,scaleY:1.13,alpha:0.069},0).wait(1).to({scaleX:1.12,scaleY:1.12,alpha:0.093},0).wait(1).to({scaleX:1.12,scaleY:1.12,alpha:0.123},0).wait(1).to({scaleX:1.11,scaleY:1.11,alpha:0.161},0).wait(1).to({scaleX:1.1,scaleY:1.1,alpha:0.21},0).wait(1).to({scaleX:1.09,scaleY:1.09,alpha:0.275},0).wait(1).to({scaleX:1.07,scaleY:1.07,alpha:0.369},0).wait(1).to({scaleX:1.04,scaleY:1.04,y:173.3,alpha:0.527},0).wait(1).to({regY:78.4,scaleX:0.95,scaleY:0.95,y:173.5,alpha:1},0).to({scaleX:1.05,scaleY:1.05},3,cjs.Ease.get(1)).to({scaleX:0.98,scaleY:0.98},2,cjs.Ease.get(-0.5)).to({scaleX:1,scaleY:1},1).wait(49).to({scaleX:1.16,scaleY:1.16,alpha:0},18,cjs.Ease.get(-1)).wait(584));

	// txt3.1
	this.instance_14 = new lib.txt31();
	this.instance_14.setTransform(178.1,-2.7,1,1,0,0,0,1.8,0.3);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(417).to({_off:false},0).to({x:1.8,y:0.3,alpha:1},22,cjs.Ease.get(1)).wait(59).to({x:172.8,alpha:0},18,cjs.Ease.get(-1)).wait(584));

	// txt3
	this.instance_15 = new lib.txt3();
	this.instance_15.setTransform(95.8,-4.2,1,1,0,0,0,95.8,36.8);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(408).to({_off:false},0).to({y:36.8,alpha:1},19,cjs.Ease.get(1)).wait(261).to({y:-15.6,alpha:0},18,cjs.Ease.get(1)).wait(394));

	// txt2
	this.instance_16 = new lib.txt2();
	this.instance_16.setTransform(0.7,1.3,1,1,0,0,0,0.7,1.3);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(325).to({_off:false},0).to({alpha:1},23,cjs.Ease.get(1)).wait(38).to({alpha:0},22,cjs.Ease.get(-1)).to({_off:true},1).wait(691));

	// dark_panel
	this.instance_17 = new lib.dp();
	this.instance_17.setTransform(723,1.5,1,1,0,0,0,1,1.5);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(287).to({_off:false},0).to({x:1},28,cjs.Ease.get(1)).wait(382).to({x:356.1,alpha:0},23,cjs.Ease.get(-1)).wait(380));

	// txt1
	this.instance_18 = new lib.txt1();
	this.instance_18.setTransform(134.4,60.3,1,1,0,0,0,134.4,60.3);
	this.instance_18.alpha = 0;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(220).to({_off:false},0).to({alpha:1},22,cjs.Ease.get(1)).wait(33).to({x:266.5,alpha:0},12,cjs.Ease.get(-1)).wait(813));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgxIAZdMAKpgy6MBXoAAAMgKoAy6g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:583.7,y:163}).wait(232).to({graphics:null,x:0,y:0}).wait(868));

	// sales
	this.instance_19 = new lib.clouth("synched",0,false);
	this.instance_19.setTransform(594.5,164.4,0.615,0.615,0,0,0,556,556);

	this.instance_19.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({regX:555.9,scaleX:0.91,scaleY:0.91,rotation:-69.7,x:586.5,y:151.4,startPosition:143},143,cjs.Ease.get(1)).wait(65).to({startPosition:200},0).to({x:456.4,startPosition:224},24,cjs.Ease.get(1)).wait(74).to({startPosition:298},0).to({x:338.4,startPosition:318},24,cjs.Ease.get(1)).wait(56).to({startPosition:374},0).to({alpha:0,startPosition:396},22,cjs.Ease.get(-1)).to({_off:true},1).wait(691));

	// fon
	this.instance_20 = new lib.fon();

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(1100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1170,326);


// stage content:
(lib._1170x326html5 = function() {
	this.initialize();

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhbZAZdMAAAgy6MC2zAAAMAAAAy6g");
	mask.setTransform(585,163);

	// about
	this.about = new lib.about();

	this.about.mask = mask;

	// background
	this.bg = new lib.background();
	this.bg.setTransform(585,163,2.127,0.815,0,0,0,275,200);

	this.addChild(this.bg,this.about);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(585,163,1170,326);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;